ansforge/IG-fhir-medicosocial-transfert-donnees-dui

input/pagecontent/index.md

* Ajout du lien vers la ressource PDSm Simplified Publish
* Mise à jour des liens de redirection vers les pages de sommaires des spécifications fonctionnes et techniques
* Mise à jour du périmètre couvert par les spécifications techniques de contenu
* correction d'une coquille de texte
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/Accueil-issues19-44/ig

ANS-006-121 - #19 - #44 - #81 - #93 - MAJ page d'accueil

---

sushi-config.yaml

* Ajout des dépendances NOS
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/issue77-AjoutDependancesNOS/ig

ANS-006-121 - #77 - Ajout dépendances NOS

---

input/pagecontent/contenu_dossier_contexte.md
input/pagecontent/contenu_dossier_corps_cda.md
input/pagecontent/contenu_dossier_entete_cda.md
input/pagecontent/contenu_dossier_structure_cda.md

* MAJ du contexte
* Suppression des doublons avec la page d'introduction de l'IG
* Enrichissement des données traitées
* ajout de la mention de l'outillage
* MAJ du titre
* Suppression du lien vers Art-Decor
* Correction de répétition dans le nom des volets
* Ajout d'un texte indiquant que seule les contraintes spécifiques au volet sont décrites dans ces spécifications
* Ajout d'une note spécifiant la nécessité de renseigner les OID en majuscule
* Ajout de l'élément de versionning relatedDocument
* correctif d'un bug d'affichage d'URL NOS sur la page structure + passage du style en haut de page 
* suppression des annexes décrites directement sur les pages de contenu (seront reportés dans la page annexe dédiée)
* Ajout directement dans le texte vers les document des références OID INS et …

ANS-006-121 - MAJ contenu - formatage, coquilles et précision

---

input/images-source/bloc_sejours.plantuml

Mise à jour du diagramme représentant la classe Sejour afin de retirer les données de la classe Solde et d'y ajouter celle du Sejour. 
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/CorrectionDiagrammeClasseSejour/ig

ANS-006-121 - #91 - Correction du diagramme classe Sejour

---

input/fsh/Profiles/TDDUIDocumentReference.fsh
sushi-config.yaml

* MAJ version dépendances FrCore : 1.1.0 -> 2.0.1
* MAJ RC Document Reference pour passer les références patient vers FrCorePatientProfile
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/MAJ_Dependancies_FrCore/ig

ANS-006-121 - issue 105 - MAJ dependances FrCore + MAJ RC documentReference

---

input/images-source/bloc_evaluation-grille.plantuml
input/images-source/bloc_evenement.plantuml
input/pagecontent/sfe_modelisation_contenu.md

Ajout dans la partie fonctionnelle de la modélisation plantuml de la grille d'évaluation et des événements concernant l'usager
* ...
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/Eric-fonctionnel-schema-evaluation/ig

Modélisation grille évaluation et événement usager

---

input/images-source/bloc_autorisations_administratives.plantuml
input/images-source/bloc_environnement_ressources.plantuml
input/images-source/bloc_sejours.plantuml
input/pagecontent/sfe_modelisation_contenu.md

Corrections fonctionnelles 
modification classe "Autorisations administratives"
Modification classe "Contact Personne Physique"
Modification classe "Séjour"

Evolutions partie fonctionnelle

---

input/images-source/bloc_evaluation-grille.plantuml
input/images-source/bloc_evenement.plantuml
input/images-source/bloc_identification_coordonnees.plantuml
input/images-source/bloc_sejours.plantuml
input/images-source/donnees_admin.plantuml
input/pagecontent/sfe_modelisation_contenu.md

Correctifs de l'issue 129.
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/Eric-fonctionnel-desc-evenement-evaluation/ig

Description fonctionnelle des ressources : Evenement Evaluation

---

input/pagecontent/index.md

Mise à jour de la page d'accueil en fonction des évolutions embarquées cette version.
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/92-accueil-mettre-à-jour-le-descriptif-pour-présenter-le-cas-dusage-ssiad-dans-les-données-techniques/ig

Mise à jour de la page d'accueil

---

input/pagecontent/securite.md

Issue 128 : modifications par rapport au texte initial.
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/128-ig-compléter-la-page-sécurité-dans-longlet-autres-ressources/ig

Mise à jour de la page sécurité

---

input/images-source/bloc_evaluation-grille.plantuml
input/images-source/bloc_evenement.plantuml
input/pagecontent/sfe_modelisation_contenu.md

Mise à jour suite aux issues #149 et #150 
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/149-partie-fonctionnelle-description-des-éléments-mos-profilés/ig

Partie fonctionnelle issues #149 et #150

---

input/pagecontent/tests.md
sushi-config.yaml

Création d'un onglet "Tests" listant les solutions de tests : 
- Validateurs FHIR
- Validateur CDA
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/CreationOngletTest/ig

ANS-006-121 - #89 - Création d'un onglet "Tests" dans le guide d'implémentation

---

input/pagecontent/contenu_dossier_entete_cda.md

* Correctifs liens templates de l'en-tête
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/CorrectionEntete/ig/contenu_dossier_entete_cda.html

ANS-006-121 - #124 - Correctif - Entête du document CDA

---

input/pagecontent/annexes_documents_reference.md
input/pagecontent/specs_cda.md
input/pagecontent/specs_fhir.md
sushi-config.yaml

* Mise à jour des documents de référence
* Création d'une page pour référencer les spécifications HL7 CDA
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/MAJAnnexes/ig

ANS-006-121 - #164 -MAJ DocReference + creation page specs CDA

---

sushi-config.yaml

* Réorganisation des menus
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/Ajustements/ig

Ajustements mineurs

---

sushi-config.yaml

Mettre à jour la version du NOS dans sushi-config.yaml

---

input/pagecontent/index.md

Ajouter la stu note redirigeant vers la version courante automatiquement dans le cas où le release label est 'ci-build' 
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/229-index-ajout-rg-sur-la-stu-note/ig

MAJ  de la stu note

---

input/images-source/bloc_droits_sociaux_sante.plantuml
input/pagecontent/sfe_modelisation_contenu.md

Ajout des ayants droit dans les couvertures sociales
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/246-sfe---ajout-ayants-droits-dans-assurancemaladieobligatoire-et-assurancemaladiecomplementaire/ig

ajout des ayants droit dans AMO et AMC

---

input/pagecontent/contenu_dossier_entete_cda.md

- Le numéro de sécurité sociale (NIR ou NIA) de l'usager est à véhiculer dans recordTarget/patientRole/id : root="1.2.250.1.213.1.4.13" si N° SS NIR ; root="1.2.250.1.213.1.4.14" si N° SS NIA
- Ajout des OID INS NIR et INS NIA pour information
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/MiseAJour_Contenu_EnTete/ig/contenu_dossier_entete_cda.html#recordtarget

ANS-006-141 - #179 - Ajout du numéro de sécurité sociale dans les ST

---

input/pagecontent/contenu_elements_transversaux.md

- Ajout du template FR-Participant
- Ajout du template FR-Performer
- Indication permettant de véhiculer le rôle d'infirmier coordinateur
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/MiseAJour_Contenu_ElementsTransversaux/ig/contenu_dossier_corps_cda.html#el%C3%A9ments-transversaux

ANS-006-141 - #172 - Mise a jour contenu éléments transversaux

---

input/fsh/instances/TDDUIBundleExample.fsh

#199 : Suppression de l'élément link
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/MiseAJour_ExempleBundle/ig/artifacts.html

ANS-006-141 - Mise à jour de l'exemple TDDUIBundleExample

---

input/fsh/CapabilityStatement/TDDUIProducteur.fsh

Correction d'une erreur dans le CS producteur au niveau de l'interaction Patch : 
rest.resource[=].interaction[0].code = #create
rest.resource[=].interaction[+].code = #patch
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/200_MAJ_CS_Producteur/ig

ANS-006-141 - MAJ Capability Statement Producteur - interaction patch

---

input/fsh/instances/TDDUIBundleExample.fsh
input/fsh/instances/TDDUIDocumentReferenceExample.fsh
input/pagecontent/annexes.md
input/pagecontent/autres_ressources.md
input/pagecontent/contenu_dossier.md
input/pagecontent/contenu_dossier_contexte.md
input/pagecontent/description_flux_synthese.md
input/pagecontent/documentation.md
input/pagecontent/site_ans.md
input/pagecontent/specs_cda.md
input/pagecontent/specs_fhir.md
sushi-config.yaml

Correction des erreurs et de plusieurs warning du QA :
- Ajout d'un titre et d'une description dans les exemples FHIR
- Mise à jour du sommaire et des liens de la partie "Annexes"
- Mise à jour du sommaire de la partie "Contenu du dossier CDA"
- Mise à jour du lien vers les jeux de valeurs CDA dans la partie "Contexte"
- Mise à jour des liens vers le détails des flux dans la partie "Synthèse des flux"
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/QA/ig/index.html

ANS-006-141 - Verification QA

---

sushi-config.yaml

Remettre le lien vers NOS 1.4.0

---

input/images-source/bloc_evaluation-grille.plantuml
input/pagecontent/sfe_modelisation_contenu.md

Dans détail evaluation : résultat champ évalué ajout JDV_ResultatQuestionEvaluation_CISIS
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/213-contenu---intégration-de-la-grille-dévaluation-aggir/ig

Ajout JDV_ResultatQuestionEvaluation_CISIS

---

publication-request.json
release-notes.md
sushi-config.yaml

Préparation à la publication de la release 1.1.0
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/283-préparation-de-la-release-110/ig

283 préparation de la release 110

---

input/data/features.yml

Mise à jour du lien vers les nouvelles issues

---

sushi-config.yaml

Maj terminology package dependency 1.1.0 --> latest

---

input/pagecontent/sfe_modelisation_contenu.md

- Dans la classe Statut on précise quels codes sont employés pour un évènement et une évaluation.
- Mettre les URL(s) canoniques des liens vers refs NOS
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/350-modélisation---statut-dun-évènement-et-dune-évaluation/ig

Modélisation - Statut d'un évènement et d'une évaluation

---

input/pagecontent/annexes_acronymes.md
input/pagecontent/sfe_modelisation_contenu.md

Dans classe TransportUsager les attributs accompagnement et aseptieRigoureuse des types indicateurs
https://ansforge.github.io/IG-fhir-medicosocial-transfert-donnees-dui/366-coquille-sfe-modélisation-contenue/ig

Coquille SFE Modélisation Contenu
